### ISSUE TITLE
Enviar para o KNoT Gateway uma nova leitura de corrente elétrica se e somente se diferir significativamente da leitura anterior

### ISSUE THREAD

**Issue by ghost** [almdac/perkw-thing#1]

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enviar para o KNoT Gateway uma nova leitura de corrente elétrica se e somente se diferir significativamente da leitura anterior](https://trello.com/c/ZJ8YLACJ/8-enviar-para-o-knot-gateway-uma-nova-leitura-de-corrente-el%C3%A9trica-se-e-somente-se-diferir-significativamente-da-leitura-anterior)

**Comment by almdac** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enviar para o KNoT Gateway uma nova leitura de corrente elétrica se e somente se diferir significativamente da leitura anterior](https://trello.com/c/ZJ8YLACJ/8-enviar-para-o-knot-gateway-uma-nova-leitura-de-corrente-el%C3%A9trica-se-e-somente-se-diferir-significativamente-da-leitura-anterior)

**Comment by almdac** [comment]
O KNoT Thing, quando identificar que o conteúdo dos parâmetros não mudaram em relação a última leitura, não enviará a mensagem para o Gateway

**Comment by ghost** [comment]
O KNoT Thing, quando identificar que o conteúdo dos parâmetros não mudaram em relação a última leitura, não enviará a mensagem para o Gateway

**Comment by ghost** [comment]
Revoking KNoT
