### ISSUE TITLE
Manter o estado da corrente elétrica inalterado caso o KNoT Thing não obtenha respostas do KNoT Gateway

### ISSUE THREAD

**Issue by ghost** [almdac/perkw-thing#2]

**Comment by almdac** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Manter o estado da corrente elétrica inalterado caso o KNoT Thing não obtenha respostas do KNoT Gateway](https://trello.com/c/8lcE8MYp/7-manter-o-estado-da-corrente-el%C3%A9trica-inalterado-caso-o-knot-thing-n%C3%A3o-obtenha-respostas-do-knot-gateway)

**Comment by ghost** [comment]
O próprio sistema KNoT já garante isso
