### ISSUE TITLE
Enviar leitura da corrente para o Gateway usando os três ponteiros nos parâmetros da função de leitura

### ISSUE THREAD

**Issue by ghost** [almdac/perkw-thing#3]

**Comment by ghost** [comment]
Aparentemente float points devem ser enviados no formato IEEE 754 para o gateway

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Salvar leitura da corrente em tempo real](https://trello.com/c/eW6SBe24/13-salvar-leitura-da-corrente-em-tempo-real)

**Comment by almdac** [comment]
O KNoT Thing, quando identificar que o conteúdo dos parâmetros não mudaram em relação a última leitura, não enviará a mensagem para o Gateway

**Comment by almdac** [comment]
*val_int = irms; 
*val_dec = 0; 
*multiplier = 1;

**Comment by ghost** [comment]
```c++
*val_int = irms;
*val_dec = 0;
*multiplier = 1;
```

**Comment by ghost** [comment]
Revoking KNoT
